### ISSUE TITLE
Sponsor Us button overlapping the venue div

### ISSUE THREAD

**Issue by ahmad19** [deccanrubyconf/drbc-2015#8]
![screen shot 2015-04-26 at 2 22 40 pm](https://cloud.githubusercontent.com/assets/2041827/7336517/d1927de0-ec1f-11e4-878f-b4b7d1fd765d.png)

**Comment by prathamesh-sonpatki** [comment]
@ahmad19 Please fix it :grin:

**Comment by ahmad19** [comment]
i m fixing it :)

**Comment by ahmad19** [comment]
PR Link: https://github.com/deccanrubyconf/drbc-2015/pull/9

**Comment by prathamesh-sonpatki** [comment]
Thanks :smile:
